name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests with Coverage
      run: |
        pytest --cov=users --cov-report=xml --cov-report=term-missing
    
    - name: Store coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml